version: '3'
services:
  php-fpm:
    build:
      dockerfile: ./docker/php/Dockerfile
      context: ./
      args:
        user: zloradnij
        uid: 1000
        workDir: ${APP_NAME}
    container_name: ${APP_NAME}-php-fpm
    restart: unless-stopped
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/books:delegated
    depends_on:
      - db
    networks:
      - books
    env_file:
      - .env

  db:
    container_name: ${APP_NAME}-mysql
    image: mysql:latest
    restart: always
    volumes:
      - books-mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    ports:
      - '8087:3306'
    expose:
      - "8087"
    networks:
      - books

  nginx:
    container_name: ${APP_NAME}-nginx
    image: nginx:latest
    restart: always
    volumes:
      - ./:/books:delegated
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8009:80'
    networks:
      - books
    depends_on:
      - php-fpm
      - db

  rabbitmq:
    image: rabbitmq:management
    container_name: ${APP_NAME}-rabbit
    restart: unless-stopped
    volumes:
      - ./docker/rabbitmq/data:/var/lib/rabbitmq/mnesia
    ports:
      - 15672:15672 # manage panel; use http://localhost:15672/
      - 5672:5672
    networks:
      - books
networks:
  books:
    driver: bridge

volumes:
  books-mysql:
